# Generated by Django 4.1.1 on 2022-10-02 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialnetwork', '0005_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pfp',
            name='user',
        ),
        migrations.AddField(
            model_name='pfp',
            name='pfp_user',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
