# Generated by Django 4.1.1 on 2022-10-02 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0010_alter_comment_author_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pfp', to='socialnetwork.pfp'),
        ),
    ]
