# Generated by Django 4.1.1 on 2022-10-02 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0007_remove_pfp_pfp_user_pfp_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pfp',
            old_name='user',
            new_name='pfp_user',
        ),
    ]
