# Generated by Django 4.1.1 on 2022-11-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=20)),
                ('correct_guess', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDrawing', models.BooleanField()),
                ('word', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
