# Generated by Django 4.1.1 on 2022-11-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doodleio', '0003_playeritem_guessedright'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeritem',
            name='timeLeft',
            field=models.IntegerField(default=60),
        ),
    ]
