# Generated by Django 4.1.1 on 2022-11-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doodleio', '0005_rename_timeleft_playeritem_starttime'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('startTime', models.IntegerField(default=60)),
                ('players', models.ManyToManyField(to='doodleio.playeritem')),
            ],
        ),
    ]
