# Generated by Django 4.1.3 on 2022-11-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doodleio", "0006_rounditem"),
    ]

    operations = [
        migrations.AddField(
            model_name="playeritem",
            name="hasDrawn",
            field=models.BooleanField(default=False),
        ),
    ]
