# Generated by Django 4.1.1 on 2022-11-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doodleio', '0007_playeritem_hasdrawn'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeritem',
            name='inLeaderBoardRoom',
            field=models.BooleanField(default=False),
        ),
    ]
