# Generated by Django 4.1.1 on 2022-10-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0002_comment_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.IntegerField(),
        ),
    ]
