# Generated by Django 4.1.1 on 2022-10-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0006_remove_pfp_user_pfp_pfp_user_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pfp',
            name='pfp_user',
        ),
        migrations.AddField(
            model_name='pfp',
            name='user',
            field=models.CharField(default='', max_length=100),
        ),
    ]
